[package]
name = "stockdata"
version = "0.1.0"
edition = "2021"

[dependencies]
fantoccini = "0.19.3"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0.219", features = ["derive"] }
